import {
  appealDeliveryFields,
  claimActionFields,
  insuranceContactFields,
  isCall,
  sourceFields,
  MODE_FAX_MAIL_WEB,
  SOURCE_ALL,
  SOURCE_CALL_WEBSITE,
  YES_NO,
} from "./common";
import type { NoteFormSchema } from "./types";
import { AR_SCENARIO_CATALOG } from "@/lib/ar-scenario-catalog";

const medicalRecords: NoteFormSchema = {
  id: "medical-records",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "modeToSendMr",
      label: "Mode to Send MR",
      type: "select",
      required: true,
      options: [...MODE_FAX_MAIL_WEB],
      noteLabel: "Mode to Send MR",
    },
    {
      id: "faxNumber",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.modeToSendMr === "Fax",
      noteLabel: "Fax Number",
    },
    {
      id: "mailingAddress",
      label: "Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.modeToSendMr === "Mail",
      noteLabel: "Mailing Address",
    },
    {
      id: "websiteLink",
      label: "Website Link",
      type: "text",
      required: true,
      showWhen: (v) => v.modeToSendMr === "Website",
      noteLabel: "Website Link",
    },
    {
      id: "timeLimit",
      label: "Time Limit",
      type: "text",
      required: true,
      placeholder: "e.g. 30 days from denial date",
      noteLabel: "Time Limit",
    },
    ...claimActionFields([
      "Need client assistance",
      "Need to submit an appeal",
      "MR sent",
      "Adjusted off the claim",
    ]),
  ],
};

const additionalInfoFromProvider: NoteFormSchema = {
  id: "additional-info-provider",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "requestedDocuments",
      label: "Requested Documents",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Requested Documents",
    },
    ...appealDeliveryFields("submission"),
    {
      id: "timeLimit",
      label: "Time Limit",
      type: "text",
      required: true,
      noteLabel: "Time Limit",
    },
    ...claimActionFields([
      "Need client assistance",
      "Need to submit an appeal",
      "Requested document sent",
      "Adjusted off the claim",
    ]),
  ],
};

const noClaimOnFile: NoteFormSchema = {
  id: "no-claim-on-file",
  fields: [
    ...sourceFields(SOURCE_CALL_WEBSITE),
    ...insuranceContactFields({ includeClearingHouseName: false }),
    {
      id: "coverageDetailsAvailable",
      label: "Is Coverage Details Available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Coverage Details Available",
    },
    {
      id: "policyEffectiveDate",
      label: "Policy Effective Date",
      type: "date",
      required: true,
      showWhen: (v) => v.coverageDetailsAvailable === "Yes",
      noteLabel: "Policy Effective Date",
    },
    {
      id: "policyStillActive",
      label: "Is policy still active?/No Termed Date",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.coverageDetailsAvailable === "Yes",
      noteLabel: "Policy still active / No termed date",
    },
    {
      id: "policyTermedDate",
      label: "Policy Termed Date",
      type: "date",
      required: true,
      showWhen: (v) =>
        v.coverageDetailsAvailable === "Yes" && v.policyStillActive === "No",
      noteLabel: "Policy Termed Date",
    },
    {
      id: "policyActiveOnDos",
      label: "Is Policy Active on DOS?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.coverageDetailsAvailable === "Yes",
      noteLabel: "Policy Active on DOS",
    },
    {
      id: "tfl",
      label: "TFL",
      type: "text",
      required: true,
      showWhen: (v) => v.policyActiveOnDos === "Yes",
      placeholder: "e.g. 365 days",
      noteLabel: "TFL",
    },
    {
      id: "claimMailingAddress",
      label: "Claim Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.policyActiveOnDos === "Yes",
      noteLabel: "Claim Mailing Address",
    },
    {
      id: "faxProvided",
      label: "Is Fax Number provided by rep or available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.policyActiveOnDos === "Yes",
      noteLabel: "Fax Number provided",
    },
    {
      id: "faxNumber",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.faxProvided === "Yes",
      noteLabel: "Fax Number",
    },
    {
      id: "payerIdProvided",
      label: "Is Payer ID provided by rep or available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.policyActiveOnDos === "Yes",
      noteLabel: "Payer ID provided",
    },
    {
      id: "payerId",
      label: "Payer ID",
      type: "text",
      required: true,
      showWhen: (v) => v.payerIdProvided === "Yes",
      noteLabel: "Payer ID",
    },
    {
      id: "additionalComment",
      label: "Additional Comment",
      type: "textarea",
      fullWidth: true,
      required: false,
      noteLabel: "Additional Comment",
    },
    {
      id: "callReference",
      label: "Call Reference#",
      type: "text",
      required: (v) => isCall(v),
      showWhen: (v) => !v.source || isCall(v),
      noteLabel: "Call Reference#",
    },
    {
      id: "action",
      label: "Action",
      type: "select",
      required: true,
      options: [
        "Resubmitted the claim",
        "Claim released to patient",
        "Faxed the claim",
      ],
      fullWidth: true,
      noteLabel: "Action",
    },
  ],
};

const claimInProcess: NoteFormSchema = {
  id: "claim-in-process",
  fields: [
    ...sourceFields(SOURCE_CALL_WEBSITE),
    ...insuranceContactFields({ includeClearingHouseName: false }),
    {
      id: "receivedDate",
      label: "Received Date",
      type: "date",
      required: true,
      noteLabel: "Received Date",
    },
    {
      id: "tat",
      label: "Turn Around Time (TAT)",
      type: "text",
      required: true,
      noteLabel: "TAT",
    },
    {
      id: "withinTat",
      label: "Is Claim Within TAT?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Within TAT",
    },
    {
      id: "reasonForDelay",
      label: "Reason for Delay",
      type: "select",
      required: true,
      options: [
        "Any Document OR Info Requested From Provider",
        "Info Requested From Patient",
        "Other Reasons",
      ],
      fullWidth: true,
      showWhen: (v) => v.withinTat === "No",
      noteLabel: "Reason for Delay",
    },
    {
      id: "documentRequested",
      label: "What Document Requested?",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) =>
        v.reasonForDelay === "Any Document OR Info Requested From Provider",
      noteLabel: "Document Requested",
    },
    {
      id: "addressToSendDocument",
      label: "Address to Send Document",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) =>
        v.reasonForDelay === "Any Document OR Info Requested From Provider",
      noteLabel: "Address to Send Document",
    },
    {
      id: "faxProvided",
      label: "Is fax# provided by rep or available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) =>
        v.reasonForDelay === "Any Document OR Info Requested From Provider",
      noteLabel: "Fax provided",
    },
    {
      id: "faxNumber",
      label: "Fax#",
      type: "text",
      required: true,
      showWhen: (v) => v.faxProvided === "Yes",
      noteLabel: "Fax#",
    },
    {
      id: "letterSentToPatient",
      label: "Is Letter Sent to Patient?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.reasonForDelay === "Info Requested From Patient",
      noteLabel: "Letter Sent to Patient",
    },
    {
      id: "timeFrame",
      label: "Time Frame",
      type: "text",
      required: true,
      showWhen: (v) => v.letterSentToPatient === "Yes",
      noteLabel: "Time Frame",
    },
    {
      id: "letterSentDate",
      label: "Date When Letter Sent",
      type: "date",
      required: true,
      showWhen: (v) => v.letterSentToPatient === "Yes",
      noteLabel: "Date When Letter Sent",
    },
    {
      id: "specifyReason",
      label: "Specify Reason",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.reasonForDelay === "Other Reasons",
      noteLabel: "Specify Reason",
    },
    ...claimActionFields([
      "Need to allow more time",
      "Claim released to patient",
      "Need client assistance",
    ]),
  ],
};

const approvedToPay: NoteFormSchema = {
  id: "approved-to-pay",
  fields: [
    ...sourceFields(SOURCE_CALL_WEBSITE),
    ...insuranceContactFields({ includeClearingHouseName: false }),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "allowedAmount",
      label: "Allowed Amount",
      type: "text",
      required: true,
      noteLabel: "Allowed Amount",
    },
    {
      id: "paidAmount",
      label: "Paid Amount",
      type: "text",
      required: true,
      noteLabel: "Paid Amount",
    },
    {
      id: "deductibleAmount",
      label: "Deductible Amount",
      type: "text",
      required: false,
      noteLabel: "Deductible Amount",
    },
    {
      id: "coinsurance",
      label: "Coinsurance",
      type: "text",
      required: false,
      noteLabel: "Coinsurance",
    },
    {
      id: "copayment",
      label: "Copayment",
      type: "text",
      required: false,
      noteLabel: "Copayment",
    },
    {
      id: "timeToExpectPayment",
      label: "Time to Expect Payment",
      type: "text",
      required: true,
      noteLabel: "Time to Expect Payment",
    },
    {
      id: "additionalComment",
      label: "Additional Comment",
      type: "textarea",
      fullWidth: true,
      required: false,
      noteLabel: "Additional Comment",
    },
    {
      id: "claimNumber",
      label: "Claim Number",
      type: "text",
      required: true,
      noteLabel: "Claim Number",
    },
    {
      id: "callReference",
      label: "Call Reference#",
      type: "text",
      required: (v) => isCall(v),
      showWhen: (v) => !v.source || isCall(v),
      noteLabel: "Call Reference#",
    },
    {
      id: "action",
      label: "Action",
      type: "select",
      required: true,
      options: ["Need to allow time", "Need client assistance"],
      fullWidth: true,
      noteLabel: "Action",
    },
  ],
};

const paidToPatient: NoteFormSchema = {
  id: "paid-to-patient",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "paidDate",
      label: "Paid Date",
      type: "date",
      required: true,
      noteLabel: "Paid Date",
    },
    {
      id: "allowedAmount",
      label: "Allowed Amount",
      type: "text",
      required: true,
      noteLabel: "Allowed Amount",
    },
    {
      id: "paidAmount",
      label: "Paid Amount",
      type: "text",
      required: true,
      noteLabel: "Paid Amount",
    },
    {
      id: "deductibleAmount",
      label: "Deductible Amount",
      type: "text",
      required: false,
      noteLabel: "Deductible Amount",
    },
    {
      id: "coinsurance",
      label: "Coinsurance",
      type: "text",
      required: false,
      noteLabel: "Coinsurance",
    },
    {
      id: "copayment",
      label: "Copayment",
      type: "text",
      required: false,
      noteLabel: "Copayment",
    },
    {
      id: "reasonPaidToPatient",
      label: "Reason for paying the claim to patient",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Reason paid to patient",
    },
    ...claimActionFields([
      "Claim released to patient",
      "Need client assistance",
    ]),
  ],
};

const patientNotIdentified: NoteFormSchema = {
  id: "patient-not-identified",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "isClaimDenied",
      label: "Is Claim Denied?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Claim Denied",
    },
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      showWhen: (v) => v.isClaimDenied === "Yes",
      noteLabel: "Denial Date",
    },
    {
      id: "repFoundPatient",
      label:
        "Was rep able to find the patient after First name, Last name, DOB or SSN search?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      noteLabel: "Rep found patient after name/DOB/SSN search",
    },
    {
      id: "whatWasIncorrect",
      label: "What was incorrect?",
      type: "select",
      required: true,
      options: [
        "First Name",
        "Last Name",
        "Complete Name",
        "DOB",
        "Policy ID",
      ],
      showWhen: (v) => v.repFoundPatient === "Yes",
      noteLabel: "What was incorrect",
    },
    ...claimActionFields([
      "Claim released to patient",
      "Updated the correct patient name and resubmitted the claim",
      "Updated the correct DOB and resubmitted the claim",
      "Updated the correct Policy ID and resubmitted the claim",
      "Need client assistance",
    ]),
  ],
};

const authorizationMissing: NoteFormSchema = {
  id: "authorization-missing",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "authAvailable",
      label: "Is Auth# available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Auth# available",
    },
    {
      id: "repAgreedReprocessAuth",
      label: "Rep agreed to reprocess?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.authAvailable === "Yes",
      noteLabel: "Rep agreed to reprocess",
    },
    {
      id: "reasonNotReprocessAuth",
      label: "Reason for not reprocessing the claim",
      type: "select",
      required: true,
      options: ["Need to Send Corrected Claim", "Auth# Invalid"],
      showWhen: (v) =>
        v.authAvailable === "Yes" && v.repAgreedReprocessAuth === "No",
      noteLabel: "Reason for not reprocessing",
    },
    {
      id: "tatReprocessAuth",
      label: "TAT for Reprocessing",
      type: "text",
      required: true,
      showWhen: (v) =>
        v.authAvailable === "Yes" && v.repAgreedReprocessAuth === "Yes",
      noteLabel: "TAT for Reprocessing",
    },
    {
      id: "correctedClaimTimeframe",
      label: "Corrected claim time frame",
      type: "text",
      required: true,
      showWhen: (v) => v.reasonNotReprocessAuth === "Need to Send Corrected Claim",
      noteLabel: "Corrected claim time frame",
    },
    {
      id: "emergencyPos",
      label: "Is claim billed with 23 or Emergency POS?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.authAvailable === "No",
      noteLabel: "Emergency POS (23)",
    },
    {
      id: "repAgreedEmergency",
      label: "Rep agreed to reprocess?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.authAvailable === "No" && v.emergencyPos === "Yes",
      noteLabel: "Rep agreed to reprocess (emergency)",
    },
    {
      id: "tatEmergency",
      label: "TAT for Reprocessing",
      type: "text",
      required: true,
      showWhen: (v) => v.repAgreedEmergency === "Yes",
      noteLabel: "TAT for Reprocessing",
    },
    {
      id: "reasonNotReprocessEmergency",
      label: "Reason for not reprocessing the claim",
      type: "text",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.repAgreedEmergency === "No",
      noteLabel: "Reason for not reprocessing",
    },
    {
      id: "repFoundAuthElsewhere",
      label: "Did rep have auth# or find auth# on hospital claim?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      showWhen: (v) => v.authAvailable === "No" && v.emergencyPos === "No",
      noteLabel: "Rep found auth# / hospital claim auth#",
    },
    {
      id: "retroAuthProcedure",
      label: "Did rep provide the procedure to obtain retro auth#?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      showWhen: (v) =>
        v.authAvailable === "No" &&
        v.emergencyPos === "No" &&
        v.repFoundAuthElsewhere === "No",
      noteLabel: "Retro auth procedure provided",
    },
    {
      id: "tatRetro",
      label: "TAT for Reprocessing",
      type: "text",
      required: true,
      showWhen: (v) => v.repFoundAuthElsewhere === "Yes",
      noteLabel: "TAT for Reprocessing",
    },
    {
      id: "procedureRetroAuth",
      label: "Procedure to obtain retro auth#",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.retroAuthProcedure === "Yes",
      noteLabel: "Procedure to obtain retro auth#",
    },
    {
      id: "appealMode",
      label: "Mode of appeal",
      type: "select",
      required: true,
      options: [...MODE_FAX_MAIL_WEB],
      showWhen: (v) => v.retroAuthProcedure === "No",
      noteLabel: "Mode of appeal",
    },
    {
      id: "appealFax",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Fax",
      noteLabel: "Fax Number",
    },
    {
      id: "appealWebsiteLink",
      label: "Website Link",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Website",
      noteLabel: "Website Link",
    },
    {
      id: "appealLimit",
      label: "Appeal Limit",
      type: "text",
      required: true,
      showWhen: (v) => Boolean(v.appealMode),
      noteLabel: "Appeal Limit",
    },
    {
      id: "appealMail",
      label: "Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.appealMode === "Mail",
      noteLabel: "Mailing Address",
    },
    ...claimActionFields([
      "Updated the Auth# and resubmitted the claim",
      "Need to allow time",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
      "Write off the claim",
    ]),
  ],
};

const nonCoveredCharges: NoteFormSchema = {
  id: "non-covered-charges",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "nonCoveredReason",
      label: "Reason for non covered",
      type: "select",
      required: true,
      options: [
        "Non covered under patient plan",
        "Non covered under provider contract",
      ],
      fullWidth: true,
      noteLabel: "Reason for non covered",
    },
    {
      id: "patientPlanReason",
      label: "Reason for non covered under patient plan",
      type: "select",
      required: true,
      options: ["DX or ICD-10 not covered", "Other Reason"],
      fullWidth: true,
      showWhen: (v) => v.nonCoveredReason === "Non covered under patient plan",
      noteLabel: "Patient plan non-covered reason",
    },
    {
      id: "providerContractReason",
      label: "Reason for non covered under provider contract",
      type: "select",
      required: true,
      options: ["CPT not covered under provider contract", "Other Reason"],
      fullWidth: true,
      showWhen: (v) =>
        v.nonCoveredReason === "Non covered under provider contract",
      noteLabel: "Provider contract non-covered reason",
    },
    {
      id: "specifyReason",
      label: "Specify Reason",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) =>
        v.patientPlanReason === "Other Reason" ||
        v.providerContractReason === "Other Reason",
      noteLabel: "Specify Reason",
    },
    {
      id: "correctedClaimTimeframe",
      label: "Time frame for corrected claim",
      type: "text",
      required: true,
      showWhen: (v) => v.patientPlanReason === "DX or ICD-10 not covered",
      noteLabel: "Time frame for corrected claim",
    },
    {
      id: "priorPaymentSameCpt",
      label:
        "Did payment receive for same CPT with same provider from same insurance",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      showWhen: (v) =>
        v.nonCoveredReason === "Non covered under provider contract",
      noteLabel: "Prior payment for same CPT",
    },
    {
      id: "repAgreesReprocess",
      label: "Rep agrees to reprocess",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.priorPaymentSameCpt === "Yes",
      noteLabel: "Rep agrees to reprocess",
    },
    {
      id: "tatReprocess",
      label: "TAT for Reprocessing",
      type: "text",
      required: true,
      showWhen: (v) => v.repAgreesReprocess === "Yes",
      noteLabel: "TAT for Reprocessing",
    },
    {
      id: "appealMode",
      label: "Mode of appeal",
      type: "select",
      required: true,
      options: [...MODE_FAX_MAIL_WEB],
      showWhen: (v) =>
        v.repAgreesReprocess === "No" || v.priorPaymentSameCpt === "No",
      noteLabel: "Mode of appeal",
    },
    {
      id: "appealFax",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Fax",
      noteLabel: "Fax Number",
    },
    {
      id: "appealWebsiteLink",
      label: "Website Link",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Website",
      noteLabel: "Website Link",
    },
    {
      id: "appealLimit",
      label: "Appeal Limit",
      type: "text",
      required: true,
      showWhen: (v) => Boolean(v.appealMode),
      noteLabel: "Appeal Limit",
    },
    {
      id: "appealMail",
      label: "Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.appealMode === "Mail",
      noteLabel: "Mailing Address",
    },
    ...claimActionFields([
      "Resubmitted the claim",
      "Claim released to patient",
      "Need client assistance",
      "Need coding assistance",
      "Need to submit an appeal",
      "Appeal sent",
    ]),
  ],
};

const timelyFiling: NoteFormSchema = {
  id: "timely-filing",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "tflLimit",
      label: "Timely filing limit stated by payer",
      type: "text",
      required: true,
      noteLabel: "TFL limit",
    },
    {
      id: "firstSubmissionDate",
      label: "First submission date (our side)",
      type: "date",
      required: true,
      noteLabel: "First submission date",
    },
    {
      id: "potfAvailable",
      label: "Is POTF available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "POTF available",
    },
    {
      id: "appealMode",
      label: "Mode of appeal",
      type: "select",
      required: true,
      options: [...MODE_FAX_MAIL_WEB],
      showWhen: (v) => v.potfAvailable === "Yes",
      noteLabel: "Mode of appeal",
    },
    {
      id: "appealFax",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Fax",
      noteLabel: "Fax Number",
    },
    {
      id: "appealMail",
      label: "Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.appealMode === "Mail",
      noteLabel: "Mailing Address",
    },
    {
      id: "appealWebsiteLink",
      label: "Website Link",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Website",
      noteLabel: "Website Link",
    },
    {
      id: "appealLimit",
      label: "Appeal Limit",
      type: "text",
      required: true,
      showWhen: (v) => v.potfAvailable === "Yes",
      noteLabel: "Appeal Limit",
    },
    ...claimActionFields([
      "Need to submit an appeal",
      "Appeal sent",
      "Write off the claim",
      "Need client assistance",
    ]),
  ],
};

const duplicateClaim: NoteFormSchema = {
  id: "duplicate-claim",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "originalClaimNumber",
      label: "Original claim number (payer)",
      type: "text",
      required: true,
      noteLabel: "Original claim number",
    },
    {
      id: "originalClaimStatus",
      label: "Original claim status",
      type: "text",
      required: true,
      noteLabel: "Original claim status",
    },
    {
      id: "sameDosCptUnits",
      label: "Same DOS / CPT / units as original?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Same DOS/CPT/units",
    },
    ...claimActionFields([
      "Adjusted off the claim",
      "Need to submit an appeal",
      "Appeal sent",
      "Need client assistance",
    ]),
  ],
};

const coordinationOfBenefits: NoteFormSchema = {
  id: "coordination-of-benefits",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "cobOrder",
      label: "COB order on DOS",
      type: "text",
      required: true,
      placeholder: "e.g. Primary UHC / Secondary Medicare",
      noteLabel: "COB order",
    },
    {
      id: "otherPayerName",
      label: "Other payer name",
      type: "text",
      required: true,
      noteLabel: "Other payer name",
    },
    {
      id: "primaryProcessed",
      label: "Has primary already processed?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Primary processed",
    },
    {
      id: "primaryClaimNumber",
      label: "Primary claim / ICN",
      type: "text",
      required: true,
      showWhen: (v) => v.primaryProcessed === "Yes",
      noteLabel: "Primary claim / ICN",
    },
    {
      id: "needsCobUpdate",
      label: "Does payer need updated COB / MSP form?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Needs COB/MSP update",
    },
    ...claimActionFields([
      "Billed correct primary",
      "Billed secondary with primary EOB",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
    ]),
  ],
};

const eligibilityBenefits: NoteFormSchema = {
  id: "eligibility-benefits",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "eligibleOnDos",
      label: "Was patient eligible on DOS?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Eligible on DOS",
    },
    {
      id: "correctMemberId",
      label: "Correct member ID / plan name",
      type: "text",
      required: true,
      noteLabel: "Correct member ID / plan",
    },
    {
      id: "benefitIssue",
      label: "Benefit / coverage issue",
      type: "select",
      required: true,
      options: [
        "Coverage terminated",
        "Service not covered",
        "Benefit maximum exhausted",
        "Incorrect member ID",
        "Other",
      ],
      fullWidth: true,
      noteLabel: "Benefit / coverage issue",
    },
    {
      id: "specifyBenefitIssue",
      label: "Specify other reason",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.benefitIssue === "Other",
      noteLabel: "Specify reason",
    },
    ...claimActionFields([
      "Updated demographics and resubmitted",
      "Claim released to patient",
      "Billed other payer",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
    ]),
  ],
};

const codingDenial: NoteFormSchema = {
  id: "coding-denial",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "denialCodes",
      label: "Denial / remark codes",
      type: "text",
      required: true,
      noteLabel: "Denial / remark codes",
    },
    {
      id: "affectedLines",
      label: "Affected CPT / ICD lines",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Affected lines",
    },
    {
      id: "codingIssueType",
      label: "Coding issue type",
      type: "select",
      required: true,
      options: [
        "Invalid modifier",
        "Modifier inconsistent with procedure",
        "Diagnosis inconsistent with procedure",
        "Bundling / inclusive",
        "Invalid CPT on DOS",
        "Other coding issue",
      ],
      fullWidth: true,
      noteLabel: "Coding issue type",
    },
    ...claimActionFields([
      "Tasked coding team",
      "Need coding assistance",
      "Resubmitted the claim",
      "Need to submit an appeal",
      "Need client assistance",
    ]),
  ],
};

const providerEnrollment: NoteFormSchema = {
  id: "provider-enrollment",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "npiTaxId",
      label: "Rendering NPI / Billing Tax ID on claim",
      type: "text",
      required: true,
      noteLabel: "NPI / Tax ID",
    },
    {
      id: "enrollmentStatus",
      label: "Enrollment status stated by payer",
      type: "text",
      required: true,
      noteLabel: "Enrollment status",
    },
    {
      id: "enrollmentEffectiveDate",
      label: "Enrollment effective date",
      type: "date",
      required: false,
      noteLabel: "Enrollment effective date",
    },
    {
      id: "willReprocessAfterEnrollment",
      label: "Will payer reprocess after enrollment update?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      noteLabel: "Reprocess after enrollment",
    },
    ...claimActionFields([
      "Tasked credentialing",
      "Need client assistance",
      "Need to allow time",
      "Need to submit an appeal",
      "Write off the claim",
    ]),
  ],
};

const secondaryBilling: NoteFormSchema = {
  id: "secondary-billing",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "primaryPayer",
      label: "Primary payer",
      type: "text",
      required: true,
      noteLabel: "Primary payer",
    },
    {
      id: "primaryPaidAmount",
      label: "Primary paid amount",
      type: "text",
      required: true,
      noteLabel: "Primary paid amount",
    },
    {
      id: "crossoverAutomatic",
      label: "Did claim crossover automatically?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Automatic crossover",
    },
    {
      id: "secondaryNeedsEob",
      label: "Does secondary need primary EOB attached?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Secondary needs primary EOB",
    },
    {
      id: "secondaryClaimNumber",
      label: "Secondary claim number",
      type: "text",
      required: false,
      noteLabel: "Secondary claim number",
    },
    ...claimActionFields([
      "Billed secondary with primary EOB",
      "Need to allow time",
      "Need client assistance",
      "Claim released to patient",
    ]),
  ],
};

const patientResponsibility: NoteFormSchema = {
  id: "patient-responsibility",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "allowedAmount",
      label: "Allowed Amount",
      type: "text",
      required: true,
      noteLabel: "Allowed Amount",
    },
    {
      id: "paidAmount",
      label: "Insurance Paid Amount",
      type: "text",
      required: true,
      noteLabel: "Insurance Paid Amount",
    },
    {
      id: "deductibleAmount",
      label: "Deductible Amount",
      type: "text",
      required: false,
      noteLabel: "Deductible Amount",
    },
    {
      id: "coinsurance",
      label: "Coinsurance",
      type: "text",
      required: false,
      noteLabel: "Coinsurance",
    },
    {
      id: "copayment",
      label: "Copayment",
      type: "text",
      required: false,
      noteLabel: "Copayment",
    },
    {
      id: "patientLiabilityReason",
      label: "Reason for patient liability",
      type: "select",
      required: true,
      options: [
        "Deductible",
        "Coinsurance",
        "Copayment",
        "Non-covered",
        "Other",
      ],
      noteLabel: "Patient liability reason",
    },
    ...claimActionFields([
      "Claim released to patient",
      "Need client assistance",
    ]),
  ],
};

const paidIncorrectly: NoteFormSchema = {
  id: "paid-incorrectly",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "allowedAmount",
      label: "Allowed Amount",
      type: "text",
      required: true,
      noteLabel: "Allowed Amount",
    },
    {
      id: "paidAmount",
      label: "Paid Amount",
      type: "text",
      required: true,
      noteLabel: "Paid Amount",
    },
    {
      id: "expectedAllowed",
      label: "Expected allowed / contracted amount",
      type: "text",
      required: true,
      noteLabel: "Expected allowed",
    },
    {
      id: "varianceReason",
      label: "Payer explanation for variance",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Variance explanation",
    },
    {
      id: "appealMode",
      label: "Mode of reconsideration / appeal",
      type: "select",
      required: false,
      options: [...MODE_FAX_MAIL_WEB],
      noteLabel: "Mode of appeal",
    },
    {
      id: "appealFax",
      label: "Fax Number",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Fax",
      noteLabel: "Fax Number",
    },
    {
      id: "appealMail",
      label: "Mailing Address",
      type: "textarea",
      required: true,
      fullWidth: true,
      showWhen: (v) => v.appealMode === "Mail",
      noteLabel: "Mailing Address",
    },
    {
      id: "appealWebsiteLink",
      label: "Website Link",
      type: "text",
      required: true,
      showWhen: (v) => v.appealMode === "Website",
      noteLabel: "Website Link",
    },
    ...claimActionFields([
      "Need to allow time",
      "Need to submit an appeal",
      "Appeal sent",
      "Accepted contractual adjustment",
      "Need client assistance",
    ]),
  ],
};

const medicalNecessity: NoteFormSchema = {
  id: "medical-necessity",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "denialCodes",
      label: "Denial / remark codes",
      type: "text",
      required: true,
      noteLabel: "Denial / remark codes",
    },
    {
      id: "documentsRequired",
      label: "Documents required for appeal",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Documents required",
    },
    ...appealDeliveryFields("appeal"),
    {
      id: "appealLimit",
      label: "Appeal Limit",
      type: "text",
      required: true,
      noteLabel: "Appeal Limit",
    },
    ...claimActionFields([
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
      "Tasked coding team",
      "Write off the claim",
    ]),
  ],
};

const claimPaid: NoteFormSchema = {
  id: "claim-paid",
  fields: [
    ...sourceFields(SOURCE_CALL_WEBSITE),
    ...insuranceContactFields({ includeClearingHouseName: false }),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "paidDate",
      label: "Paid Date",
      type: "date",
      required: true,
      noteLabel: "Paid Date",
    },
    {
      id: "allowedAmount",
      label: "Allowed Amount",
      type: "text",
      required: true,
      noteLabel: "Allowed Amount",
    },
    {
      id: "paidAmount",
      label: "Paid Amount",
      type: "text",
      required: true,
      noteLabel: "Paid Amount",
    },
    {
      id: "deductibleAmount",
      label: "Deductible Amount",
      type: "text",
      required: false,
      noteLabel: "Deductible Amount",
    },
    {
      id: "coinsurance",
      label: "Coinsurance",
      type: "text",
      required: false,
      noteLabel: "Coinsurance",
    },
    {
      id: "copayment",
      label: "Copayment",
      type: "text",
      required: false,
      noteLabel: "Copayment",
    },
    {
      id: "checkEftNumber",
      label: "Check / EFT Number",
      type: "text",
      required: true,
      noteLabel: "Check / EFT Number",
    },
    ...claimActionFields([
      "Payment posted / confirmed",
      "Need to allow time for payment posting",
      "Need client assistance",
    ]),
  ],
};

const claimPaidOffset: NoteFormSchema = {
  id: "claim-paid-offset",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "processedDate",
      label: "Processed Date",
      type: "date",
      required: true,
      noteLabel: "Processed Date",
    },
    {
      id: "paidAmount",
      label: "Paid Amount on this claim",
      type: "text",
      required: true,
      noteLabel: "Paid Amount",
    },
    {
      id: "offsetAmount",
      label: "Offset Amount",
      type: "text",
      required: true,
      noteLabel: "Offset Amount",
    },
    {
      id: "offsetClaimNumber",
      label: "Offset applied to claim#",
      type: "text",
      required: true,
      noteLabel: "Offset claim#",
    },
    {
      id: "offsetReason",
      label: "Reason for offset",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Offset reason",
    },
    ...claimActionFields([
      "Offset accepted / documented",
      "Need client assistance",
      "Need to submit an appeal",
    ]),
  ],
};

const referralMissing: NoteFormSchema = {
  id: "referral-missing",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "referralRequired",
      label: "Was referral required?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Referral required",
    },
    {
      id: "referralOnFile",
      label: "Is referral# on file?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Referral on file",
    },
    {
      id: "referralNumber",
      label: "Referral Number",
      type: "text",
      required: true,
      showWhen: (v) => v.referralOnFile === "Yes",
      noteLabel: "Referral Number",
    },
    {
      id: "repAgreedReprocess",
      label: "Rep agreed to reprocess?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      showWhen: (v) => v.referralOnFile === "Yes",
      noteLabel: "Rep agreed to reprocess",
    },
    ...appealDeliveryFields("appeal"),
    {
      id: "appealLimit",
      label: "Appeal Limit",
      type: "text",
      required: true,
      showWhen: (v) => v.referralOnFile === "No" || v.repAgreedReprocess === "No",
      noteLabel: "Appeal Limit",
    },
    ...claimActionFields([
      "Updated referral and resubmitted",
      "Need to allow time",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
      "Claim released to patient",
    ]),
  ],
};

const maxBenefit: NoteFormSchema = {
  id: "max-benefit",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "benefitMaximum",
      label: "Benefit maximum applied",
      type: "text",
      required: true,
      noteLabel: "Benefit maximum",
    },
    {
      id: "benefitPeriod",
      label: "Benefit period / units used",
      type: "text",
      required: true,
      noteLabel: "Benefit period / units",
    },
    {
      id: "remainingBenefit",
      label: "Remaining benefit available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Remaining benefit",
    },
    ...claimActionFields([
      "Claim released to patient",
      "Billed secondary",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
    ]),
  ],
};

const outOfNetwork: NoteFormSchema = {
  id: "out-of-network",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "providerOon",
      label: "Is provider out of network for this plan?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Provider OON",
    },
    {
      id: "oonBenefits",
      label: "Are out-of-network benefits available?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "OON benefits available",
    },
    {
      id: "exceptionOnFile",
      label: "Gap exception / single-case agreement on file?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Exception on file",
    },
    ...claimActionFields([
      "Claim released to patient",
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
    ]),
  ],
};

const infoFromPatient: NoteFormSchema = {
  id: "info-from-patient",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial / pend date",
      type: "date",
      required: true,
      noteLabel: "Denial / pend date",
    },
    {
      id: "infoRequested",
      label: "Information requested from patient",
      type: "textarea",
      required: true,
      fullWidth: true,
      noteLabel: "Info requested from patient",
    },
    {
      id: "letterSent",
      label: "Was a letter sent to patient?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "Letter sent",
    },
    {
      id: "letterSentDate",
      label: "Date letter sent",
      type: "date",
      required: true,
      showWhen: (v) => v.letterSent === "Yes",
      noteLabel: "Letter sent date",
    },
    {
      id: "waitDays",
      label: "Days payer will wait for patient response",
      type: "text",
      required: true,
      noteLabel: "Wait days",
    },
    ...claimActionFields([
      "Need to allow more time",
      "Claim released to patient",
      "Need client assistance",
    ]),
  ],
};

const hospice: NoteFormSchema = {
  id: "hospice",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "hospiceElectionDates",
      label: "Hospice election dates",
      type: "text",
      required: true,
      noteLabel: "Hospice election dates",
    },
    {
      id: "serviceRelatedToHospice",
      label: "Is billed service related to hospice diagnosis?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      noteLabel: "Service related to hospice",
    },
    {
      id: "correctBillingParty",
      label: "Correct billing party / payer if not this claim",
      type: "text",
      required: false,
      noteLabel: "Correct billing party",
    },
    ...claimActionFields([
      "Need client assistance",
      "Need to submit an appeal",
      "Appeal sent",
      "Write off the claim",
      "Claim released to patient",
    ]),
  ],
};

const capitation: NoteFormSchema = {
  id: "capitation",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial / status date",
      type: "date",
      required: true,
      noteLabel: "Denial / status date",
    },
    {
      id: "providerCapitated",
      label: "Is provider capitated for this plan on DOS?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      fullWidth: true,
      noteLabel: "Provider capitated",
    },
    {
      id: "carveOut",
      label: "Is CPT carved out of capitation?",
      type: "yesno",
      required: true,
      options: [...YES_NO],
      noteLabel: "CPT carved out",
    },
    ...claimActionFields([
      "Adjusted off the claim",
      "Claim released to patient",
      "Need client assistance",
      "Need to submit an appeal",
    ]),
  ],
};

const otherLiability: NoteFormSchema = {
  id: "other-liability",
  fields: [
    ...sourceFields(SOURCE_ALL),
    ...insuranceContactFields(),
    {
      id: "denialDate",
      label: "Denial Date",
      type: "date",
      required: true,
      noteLabel: "Denial Date",
    },
    {
      id: "liabilityType",
      label: "Liability type",
      type: "select",
      required: true,
      options: [
        "Worker's Compensation",
        "Liability carrier",
        "No-fault / Auto",
      ],
      noteLabel: "Liability type",
    },
    {
      id: "otherCarrierName",
      label: "Other carrier name",
      type: "text",
      required: true,
      noteLabel: "Other carrier name",
    },
    {
      id: "otherClaimNumber",
      label: "Other carrier claim number",
      type: "text",
      required: true,
      noteLabel: "Other carrier claim#",
    },
    {
      id: "accidentDate",
      label: "Date of accident / injury",
      type: "date",
      required: false,
      noteLabel: "Accident / injury date",
    },
    ...claimActionFields([
      "Billed other payer",
      "Need client assistance",
      "Need to submit an appeal",
    ]),
  ],
};

const NOTE_SCHEMA_BY_ID: Record<string, NoteFormSchema> = {
  noClaimOnFile,
  claimInProcess,
  approvedToPay,
  claimPaid,
  claimPaidOffset,
  paidToPatient,
  patientResponsibility,
  patientNotIdentified,
  eligibilityBenefits,
  timelyFiling,
  authorizationMissing,
  referralMissing,
  maxBenefit,
  nonCoveredCharges,
  outOfNetwork,
  infoFromPatient,
  additionalInfoFromProvider,
  medicalRecords,
  duplicateClaim,
  hospice,
  codingDenial,
  providerEnrollment,
  secondaryBilling,
  coordinationOfBenefits,
  capitation,
  medicalNecessity,
  otherLiability,
  paidIncorrectly,
};

/** Map content section + slug → note form schema */
export const NOTE_FORM_REGISTRY: Record<string, NoteFormSchema> = {};

for (const entry of AR_SCENARIO_CATALOG) {
  const schema = NOTE_SCHEMA_BY_ID[entry.noteSchema];
  if (!schema) {
    throw new Error(
      `Missing note schema "${entry.noteSchema}" for ${entry.slug}`,
    );
  }
  const section = entry.kind === "denial" ? "denials" : "scenarios";
  NOTE_FORM_REGISTRY[`${section}/${entry.slug}`] = schema;
}

export function getNoteFormSchema(
  section: string,
  slug: string,
): NoteFormSchema | null {
  return NOTE_FORM_REGISTRY[`${section}/${slug}`] ?? null;
}

/** Safe for Server Components — returns a boolean only (no functions). */
export function hasNoteForm(section: string, slug: string): boolean {
  return `${section}/${slug}` in NOTE_FORM_REGISTRY;
}

export {
  medicalRecords,
  additionalInfoFromProvider,
  noClaimOnFile,
  claimInProcess,
  approvedToPay,
  paidToPatient,
  patientNotIdentified,
  authorizationMissing,
  nonCoveredCharges,
  timelyFiling,
  duplicateClaim,
};
